name: "Multiple Event Checker"

on:
  push:
    branches:
      - main
      - tryout

  pull_request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Printing"
        run:
          echo "HelloWorld!"
          echo "Actor: $GITHUB_ACTOR"

